"""Initial schema with expanded models

Revision ID: 10740efec864
Revises: 
Create Date: 2025-12-17 07:43:55.879769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10740efec864'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_data_quality_entity', 'data_quality_flags', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_data_quality_flag_type', 'data_quality_flags', ['flag_type'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_sha256'), 'media_assets', ['sha256'], unique=True)
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('xref', sa.String(length=255), nullable=True),
    sa.Column('given', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('birth_date', sa.String(length=255), nullable=True),
    sa.Column('birth_place', sa.String(length=255), nullable=True),
    sa.Column('death_date', sa.String(length=255), nullable=True),
    sa.Column('death_place', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_persons_name', 'persons', ['surname', 'given'], unique=False)
    op.create_index(op.f('ix_persons_xref'), 'persons', ['xref'], unique=True)
    op.create_table('places',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_canonical', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_canonical')
    )
    op.create_table('families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('xref', sa.String(length=255), nullable=True),
    sa.Column('husband_person_id', sa.Integer(), nullable=True),
    sa.Column('wife_person_id', sa.Integer(), nullable=True),
    sa.Column('marriage_date', sa.String(length=255), nullable=True),
    sa.Column('marriage_place', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['husband_person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wife_person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_xref'), 'families', ['xref'], unique=True)
    op.create_table('place_variants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('name_variant', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_variant')
    )
    op.create_table('relationships',
    sa.Column('parent_person_id', sa.Integer(), nullable=False),
    sa.Column('child_person_id', sa.Integer(), nullable=False),
    sa.Column('rel_type', sa.String(length=50), server_default='parent', nullable=False),
    sa.ForeignKeyConstraint(['child_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_person_id', 'child_person_id', 'rel_type')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('BIRTH', 'DEATH', 'MARRIAGE', 'DIVORCE', 'CENSUS', 'RESIDENCE', 'OCCUPATION', 'IMMIGRATION', 'EMIGRATION', 'NATURALIZATION', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('date_raw', sa.String(length=255), nullable=True),
    sa.Column('place_raw', sa.String(length=255), nullable=True),
    sa.Column('date_canonical', sa.DateTime(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_date_canonical', 'events', ['date_canonical'], unique=False)
    op.create_index('idx_events_family', 'events', ['family_id'], unique=False)
    op.create_index('idx_events_person', 'events', ['person_id'], unique=False)
    op.create_table('family_children',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('child_person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('family_id', 'child_person_id')
    )
    op.create_table('media_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_links_family', 'media_links', ['family_id'], unique=False)
    op.create_index('idx_media_links_person', 'media_links', ['person_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_index('idx_media_links_person', table_name='media_links')
    op.drop_index('idx_media_links_family', table_name='media_links')
    op.drop_table('media_links')
    op.drop_table('family_children')
    op.drop_index('idx_events_person', table_name='events')
    op.drop_index('idx_events_family', table_name='events')
    op.drop_index('idx_events_date_canonical', table_name='events')
    op.drop_table('events')
    op.drop_table('relationships')
    op.drop_table('place_variants')
    op.drop_index(op.f('ix_families_xref'), table_name='families')
    op.drop_table('families')
    op.drop_table('places')
    op.drop_index(op.f('ix_persons_xref'), table_name='persons')
    op.drop_index('idx_persons_name', table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_media_assets_sha256'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('idx_data_quality_flag_type', table_name='data_quality_flags')
    op.drop_index('idx_data_quality_entity', table_name='data_quality_flags')
    op.drop_table('data_quality_flags')
    # ### end Alembic commands ###
